name: translation_intelligence_server
description: Backend API for Translation Intelligence
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0

dependencies:
  googleapis_auth: ^2.2.0
  http: ^1.6.0
  logging: ^1.3.0
  shelf: ^1.4.2
  shelf_router: ^1.1.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
