// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrDpfy_ZwGXz0my-SxDHj9dwDV3Q_coKc',
    appId: '1:807627897911:web:0881cbefcc13b9af4813b2',
    messagingSenderId: '807627897911',
    projectId: 'tutti-lingo',
    authDomain: 'tutti-lingo.firebaseapp.com',
    storageBucket: 'tutti-lingo.firebasestorage.app',
    measurementId: 'G-S0X5GBT0F3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDCTRkDbXpsnLzfpewRaOEo3-LOgxv-p8',
    appId: '1:807627897911:android:3b03bc1d57cbfb264813b2',
    messagingSenderId: '807627897911',
    projectId: 'tutti-lingo',
    storageBucket: 'tutti-lingo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlxM7iI7AT6w-wkFq8smY2COViRQ0Y3sQ',
    appId: '1:807627897911:ios:6a7fc172d14770d94813b2',
    messagingSenderId: '807627897911',
    projectId: 'tutti-lingo',
    storageBucket: 'tutti-lingo.firebasestorage.app',
    iosBundleId: 'com.example.translationIntelligence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlxM7iI7AT6w-wkFq8smY2COViRQ0Y3sQ',
    appId: '1:807627897911:ios:6a7fc172d14770d94813b2',
    messagingSenderId: '807627897911',
    projectId: 'tutti-lingo',
    storageBucket: 'tutti-lingo.firebasestorage.app',
    iosBundleId: 'com.example.translationIntelligence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrDpfy_ZwGXz0my-SxDHj9dwDV3Q_coKc',
    appId: '1:807627897911:web:5f363a7f798da4ab4813b2',
    messagingSenderId: '807627897911',
    projectId: 'tutti-lingo',
    authDomain: 'tutti-lingo.firebaseapp.com',
    storageBucket: 'tutti-lingo.firebasestorage.app',
    measurementId: 'G-G5JLK9PT9T',
  );
}
