name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: touch .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Install server dependencies
        run: |
          cd server
          dart pub get

      - name: Run Flutter Analyzer
        run: flutter analyze

  app_test:
    name: Flutter Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: touch .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

  coverage:
    name: Coverage Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: touch .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Check coverage
        run: dart run tool/test_with_coverage.dart

  server_test:
    name: Server Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: touch .env

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.11.0'

      - name: Install server dependencies
        run: |
          cd server
          dart pub get

      - name: Run server tests
        run: |
          cd server
          dart test
